language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install ./fpgaedu
  - pip install myhdl 
  - pip install pytest
# command to run tests
script: py.test
